test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.83014f57450daf58746e7fb79003f52ad8d2da1e.name = "Upgrade from 2.21"
